Draft an app with all essential features
Blef-team/blef_android_app pull request #2
Opened 2021-07-10 11:36 UTC by maciej-pomykala

2021-12-02 22:38 UTC, adrian-golian requested changes
I won't delude myself that this is (can be) a solid review, but I do point out a couple of things.

2021-12-02 22:38 UTC, adrian-golian commented on README.md
> +This repository contains the Android Studio project and assets for the iOS game Blef. The app makes use of the Blef game engine API service.
Yeah, no 😄

2021-12-02 22:38 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/Creating.kt
> +                .url("https://n4p6oovxsg.execute-api.eu-west-2.amazonaws.com/games/create")
Refactor the base url to set it once for the whole app? (defined 7 separate times right now)
https://github.com/Blef-team/blef_ios_app/search?q=https%3A%2F%2Fn4p6oovxsg.execute

2021-12-02 22:38 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/Game.kt
> +            val tryingNickname = rawNickname.replace(" ", "_")
User input should probably be more sanitised than that.

2021-12-02 22:38 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/Game.kt
> +                gameObject.getString("status") == "Not started" -> {
Should probably use status [enums](https://kotlinlang.org/docs/enum-classes.html) instead of raw strings. (throughout the app)

2021-12-02 22:38 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/MainActivity.kt
> +        //startActivity(intent)
Remove commented-out code

2021-12-02 23:53 UTC, maciej-pomykala commented on app/src/main/java/app/blef/blef/Game.kt
> +            val tryingNickname = rawNickname.replace(" ", "_")
This replacement is because we've figured out we'll leave underscores to help people have spaces in nicknames without breaking the engine. The app later replaces the underscore with a space when displaying the nickname.
As such, there's no sanitising really. What do you mean I do with other illegal characters (like numbers at the beginning)? Strip them off without asking the user? Right now, the user will have the engine error relayed to them.

2021-12-03 00:01 UTC, maciej-pomykala commented on app/src/main/java/app/blef/blef/Game.kt
> +                gameObject.getString("status") == "Not started" -> {
What's the benefit of enums in this case?

2021-12-03 03:11 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/Game.kt
> +                gameObject.getString("status") == "Not started" -> {
Move from a potential run-time error to a compil-time error (+ IDE support). That's the benefit of enums generally, not just in this case.

2021-12-03 03:13 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/Game.kt
> +            val tryingNickname = rawNickname.replace(" ", "_")
I don't mean 'illegal' characters, I mean _malicious_ characters. I'm sure you'd agree no quotes, ticks, back/forward-slashes, colons, semi-colons etc. etc.

2021-12-03 03:15 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/Game.kt
> +            val tryingNickname = rawNickname.replace(" ", "_")
Executing whatever the user cooked up for you might end up bad.

2021-12-03 13:30 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/Game.kt
> +                gameObject.getString("status") == "Not started" -> {
https://github.com/Blef-team/blef_ios_app/search?q=enum%20Status

2021-12-04 13:00 UTC, adrian-golian commented on app/src/main/java/app/blef/blef/Game.kt
> +                gameObject.getString("status") == "Not started" -> {
https://github.com/Blef-team/blef_ios_app/blob/fc816fd2a96615b8dca7302edff642775c19e329/Blef/Game.swift#L34

https://github.com/Blef-team/blef_ios_app/search?q=.notStarted
https://github.com/Blef-team/blef_ios_app/search?q=.running
https://github.com/Blef-team/blef_ios_app/search?q=.finished

2021-12-04 19:36 UTC, adrian-golian commented
Great query refactor 👍

2021-12-06 19:04 UTC, adrian-golian approved these changes

2021-12-06 19:04 UTC, adrian-golian commented
:shipit:

2021-12-06 19:05 UTC, adrian-golian commented
Link to issue before merge?

2021-12-06 19:38 UTC, merged